version: '3'
services:
  #Nginx Service
  proxy.laravel.com:
    container_name: proxy.laravel.com
    image: jwilder/nginx-proxy:latest
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      main:
        aliases:
          - proxy.laravel.com

  #PHP Service
  app.laravel.com:
    container_name: app.laravel.com
    image: laravel-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    ports:
      - 80
    depends_on: 
      - db.laravel.com
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      VIRTUAL_HOST: 'app.laravel.com'
      VIRTUAL_PORT: 80
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: 'base64:773f72eCRgzJTqM88Dp4QgA9Gvx5rFw9IJEWu9hlDdc='
      APP_DEBUG: 'true'
      APP_URL: 'http://app.laravel.com'
      DB_HOST: "db.laravel.com"
      DB_USERNAME: "root"
      DB_DATABASE: "laravel"
      DB_PASSWORD: "1234"
      DB_PORT: "3306"
      DB_CONNECTION: "mysql"
    command: "php artisan serve --host=0.0.0.0 --port=80"
    networks:
      main:
        aliases:
          - app.laravel.com

  #MySQL Service
  db.laravel.com:
    container_name: db.laravel.com
    image: mariadb:10.2.19
    volumes:
      - "./.data:/var/lib/mysql"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: unless-stopped
    networks:
      main:
        aliases:
          - db.laravel.com

#Docker Networks
networks:
  main:
